# Generated by Django 3.0.2 on 2020-02-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunli', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
